#RabbitMQ Configuration
spring:
  cloud:
    function:
      definition: userEventConsumer; foodEventConsumer; recipeEventConsumer;
    stream:
      bindings:
        eventPublisher-out-0:
          destination: list.events
          binder: cloud_rabbit
        userEventConsumer-in-0:
          destination: user.events
          group: listQueue
          binder: cloud_rabbit
        foodEventConsumer-in-0:
          destination: food.events
          group: listQueue
          binder: cloud_rabbit
        recipeEventConsumer-in-0:
          destination: recipe.events
          group: listQueue
          binder: cloud_rabbit
      binders:
        cloud_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                #virtual-host: guest

  #rabbitmq Daten zur Durchführung der Health Checks
  rabbitmq:
    host: localhost
    username: guest
    password: guest
