#RabbitMQ Configuration
spring:
  cloud:
    function:
      definition: eventPublisher; userEventConsumer; productEventConsumer;
    stream:
      bindings:
        eventPublisher-out-0:
          destination: list.events
          binder: cloud_rabbit
        userEventConsumer-in-0:
          destination: user.events
          binder: cloud_rabbit
        foodEventConsumer-in-0:
          destination: food.events
          binder: cloud_rabbit
        recipeEventConsumer-in-0:
          destination: recipe.events
          binder: cloud_rabbit
      binders:
        cloud_rabbit:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: rabbitmq.team02.svc.cluster.local
                  port: 15672
                  username: admin
                  password: PHz55LqQuj
                  virtual-host: guest
      rabbit:
        bindings:
          input:
            consumer:
              exchange-type: fanout
          output:
            consumer:
              exchange-type: fanout

#rabbitmq Daten zur Durchführung der Health Checks
rabbitmq:
  host: rabbitmq.team02.svc.cluster.local
  username: admin
  password: PHz55LqQuj