#RabbitMQ Configuration
spring:
  cloud:
    function:
      definition: userEventConsumer;foodEventConsumer;recipeEventConsumer;
    stream:
      rabbit:
        bindings:
          eventPublisher-out-0:
            producer:
              transacted: true
          userEventConsumer-in-0:
            consumer:
              transacted: true
              max-attempts: 3
          foodEventConsumer-in-0:
            consumer:
              transacted: true
              max-attempts: 3
          recipeEventConsumer-in-0:
            consumer:
              transacted: true
              max-attempts: 3
      bindings:
        eventPublisher-out-0:
          destination: list.events
          binder: cloud_rabbit
        userEventConsumer-in-0:
          destination: user.events
          group: listQueue
          binder: cloud_rabbit
        foodEventConsumer-in-0:
          destination: food.events
          group: listQueue
          binder: cloud_rabbit
        recipeEventConsumer-in-0:
          destination: recipe.events
          group: listQueue
          binder: cloud_rabbit
      binders:
        cloud_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: goose-01.rmq2.cloudamqp.com
                port: 5672
                username: ejnvcsrm
                password: TYKDzrPXmD9t37A-GuL_RjCqSuTkE8CE
                virtual-host: ejnvcsrm
  #rabbitmq Daten zur Durchführung der Health Checks
  rabbitmq:
    host: goose-01.rmq2.cloudamqp.com
    username: ejnvcsrm
    password: TYKDzrPXmD9t37A-GuL_RjCqSuTkE8CE