#RabbitMQ Configuration
spring:
  cloud:
    function:
      definition: deletedEventConsumer; registeredEventConsumer
      stream:
        bindings:
          eventPublisher-out-0:
            destination: test.list.events
            binder: cloud_rabbit
          userEventConsumer-in-0:
            destination: test.user.events
            binder: cloud_rabbit
          foodEventConsumer-in-0:
            destination: test.food.events
            binder: cloud_rabbit
          recipeEventConsumer-in-0:
            destination: test.recipe.events
            binder: cloud_rabbit
      binders:
        cloud_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq.team02.svc.cluster.local
                port: 5672
                username: admin
                password: PHz55LqQuj
                #virtual-host: guest

#rabbitmq Daten zur Durchführung der Health Checks
  rabbitmq:
    host: rabbitmq.team02.svc.cluster.local
    username: admin
    password: PHz55LqQuj
