#RabbitMQ Configuration
spring:
  cloud:
    function:
      definition: userEventConsumer;foodEventConsumer;recipeEventConsumer;
    stream:
      rabbit:
        bindings:
          eventPublisher-out-0:
            producer:
              transacted: true
          userEventConsumer-in-0:
            consumer:
              transacted: true
              max-attempts: 3
          foodEventConsumer-in-0:
            consumer:
              transacted: true
              max-attempts: 3
          recipeEventConsumer-in-0:
            consumer:
              transacted: true
              max-attempts: 3
      bindings:
        eventPublisher-out-0:
          destination: test.list.events
          binder: cloud_rabbit
        userEventConsumer-in-0:
          destination: test.user.events
          group: test-listQueue
          binder: cloud_rabbit
        foodEventConsumer-in-0:
          destination: test.food.events
          group: test-listQueue
          binder: cloud_rabbit
        recipeEventConsumer-in-0:
          destination: test.recipe.events
          group: test-listQueue
          binder: cloud_rabbit
      binders:
        cloud_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: sparrow-01.rmq.cloudamqp.com
                port: 5672
                username: hnafxwho
                password: qWdpOaHV48Rsi6hKGYS6PuE5lMXcxCUF
                virtual-host: hnafxwho
  #rabbitmq Daten zur Durchführung der Health Checks
  rabbitmq:
    host: sparrow-01.rmq.cloudamqp.com
    username: hnafxwho
    password: qWdpOaHV48Rsi6hKGYS6PuE5lMXcxCUF
    virtual-host: hnafxwho
